######### 基础配置 #########
experiment_name: "yolo26_det"
task_type: "infer"

######### 模型配置 #########
model: "/mnt/pfs-baidu/public/qing.chen/inspection/ckpts/yolo26n.pt"
device: "cuda"
conf_threshold: 0.25
iou_threshold: 0.45

######### 数据配置 #########
input_path: "/mnt/pfs-baidu/public/qing.chen/inspection/data/inspect_videos/webdamages/AL4-AL108A3-M1-25017-20250527110306.mp4"
# input_path: "/mnt/pfs-baidu/public/muyuan.zhang/ultralytics-main/data/bus.jpg"
max_frames: 500
frame_skip: 1

######### 评估配置 #########
eval_enabled: false
gt_annotation_file: ""  # COCO格式标注文件，用于评估

######### 输出配置 #########
is_save: true           # 总开关：是否保存任何输出
save_pic: true        # 视频输入时，是否保存为MP4视频（需 is_save=true）
save_video: true        # 视频输入时，是否保存为MP4视频（需 is_save=true）
save_json: true         # 是否保存JSON结果

######### 训练配置#########
path: /mnt/pfs-baidu/public/muyuan.zhang/MEC_WX_6099_YKZX
train: /mnt/pfs-baidu/public/muyuan.zhang/MEC_WX_6099_YKZX/train.txt
val: /mnt/pfs-baidu/public/muyuan.zhang/MEC_WX_6099_YKZX/val.txt
nc: 7
names:
  0: barricade
  1: biker
  2: bus
  3: car
  4: person
  5: plate
  6: truck