######### 基础配置 #########
experiment_name: "yolo26_seg"
task_type: "segment"

######### 模型配置 #########
# model: "/mnt/pfs-baidu/public/qing.chen/inspection/ckpts/yolo26n-seg.pt"
model: "/mnt/pfs-baidu/public/qing.chen/inspection/ultralytics_inspection26/ckpts/seg_tree_0628.pt"
device: "cuda"
imgsz: 640
amp: false

######### 数据配置 #########
input_path: "/mnt/pfs-baidu/public/qing.chen/inspection/ultralytics_inspection26/data/20260610-104732.jpg"
# input_path: "/mnt/pfs-baidu/public/qing.chen/inspection/ultralytics_inspection26/data/bus.jpg"

max_frames: 500
frame_skip: 1

######### 评估配置 #########
eval_enabled: false
conf_threshold: 0.25
iou_threshold: 0.45
gt_annotation_file: "" # COCO格式标注文件，用于自定义评估

########## 训练配置#########
batch: 2
epochs: 300
workers: 8
path: /mnt/pfs-baidu/public/qing.chen/inspection/datasets/seg_tree_yolo
train: images/train
val: images/val
nc: 1
names:
  0: tree

######### 输出配置 #########
is_save: true # 总开关：是否保存任何输出
save_pic: true # 视频输入时，是否保存为MP4视频（需 is_save=true）
save_video: true # 视频输入时，是否保存为MP4视频（需 is_save=true）
save_json: true # 是否保存JSON结果
