######### 基础配置 #########
experiment_name: "yolo26_seg"
task_type: "segment"

######### 模型配置 #########
model: "/mnt/pfs-baidu/public/qing.chen/inspection/ckpts/yolo26n-seg.pt"
device: "cuda"
imgsz: 640
batch: 2
epochs: 300
workers: 8
amp: false

######### 评估配置 #########
eval_enabled: false
conf_threshold: 0.25
iou_threshold: 0.45
gt_annotation_file: ""  # COCO格式标注文件，用于自定义评估

######### 训练数据配置（与 yolo26_det.yaml 同格式）#########
path: /mnt/pfs-baidu/public/qing.chen/inspection/datasets/seg_tree_coco
train: images/train
val: images/val
nc: 1
names:
  0: tree